# Generated by Django 5.1.7 on 2025-03-10 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_created_at_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message="Tags must be comma-separated words with only letters (e.g., 'pancakes,breakfast,delicious').", regex='^[a-zA-Z]+(,[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=72, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title can only contain letters, numbers, and spaces.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
